### ISSUE TITLE
2081 calendar date checks

### ISSUE THREAD

**Issue by rajbinms** [sbmdkl/nepali-date-converter#2]
Hi, came across a 2081 calendar dates issue:
Jestha 31 -> 32
Ashar 32 -> 31
Falgun  30 -> 29
Chaitra  30 -> 31

Any chance of release any time soon?

**Comment by sbmdkl** [comment]
Fixed by [PR#3](https://github.com/sbmdkl/nepali-date-converter/pull/3) please update the package to latest version (2.0.3).
