### ISSUE TITLE
Incorrect Number of days in t array

### ISSUE THREAD

**Issue by pokhrelrewant** [sbmdkl/nepali-date-converter#4]
Incorrect Number of days in t array in 2081 BS for months Jestha, Ashar, Falgun and Chaitra. Similar to the issue in Datepicker component. Should I expect a new release anytime soon?

**Comment by sbmdkl** [comment]
Fixed by [PR#3](https://github.com/sbmdkl/nepali-date-converter/pull/3) please update the package to latest version (2.0.3).
